### ISSUE TITLE
Make this isolate run in a background service

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#1104]
Perhaps use this package? https://pub.dev/packages/flutter_background_service

**Comment by jlw4049** [comment]
Can be closed here right?

**Comment by kevmo314** [comment]
Well, I guess not technically. It needs this PR https://github.com/muxable/rtchat/pull/1150

**Comment by kevmo314** [comment]
@jlw4049 if you can verify it works on android, review the PR with @SputNikPlop

**Comment by jlw4049** [comment]
Checking right now!

**Comment by SputNikPlop** [comment]
@kevmo314 @jlw4049 Good to close now?

**Comment by jlw4049** [comment]
Yes it should be good to close now!
