### ISSUE TITLE
Have the isolate listen to shared preferences on the key "tts_channel"

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#1105]
We will have to switch to a different library to listen to shared_preferences, maybe something like https://pub.dev/documentation/streaming_shared_preferences/latest/

In the `void main()` function, add a `.listen((pref) {})` callback that is called when `tts_channel` changes.

**Comment by SputNikPlop** [comment]
@jlw4049 Did this work as expected when you tested it?

**Comment by jlw4049** [comment]
I believe so but i'm double checking now
