### ISSUE TITLE
[chat_history] follow notifications

### ISSUE THREAD

**Issue by SputNikPlop** [muxable/rtchat#1128]
to fix this we should probably delete any existing eventsub subscriptions before resubscribing here: https://github.com/muxable/rtchat/blob/main/functions/src/eventsub.ts#L93C4-L93C4

**Comment by SputNikPlop** [comment]
@kevmo314 The follow notifications now are partially working they seem to be duplicating.
![IMG_2747](https://github.com/muxable/rtchat/assets/100245448/9ae24d37-e6f8-4b9d-b97d-6c26c365b6ee)

**Comment by kevmo314** [comment]
> @kevmo314 The follow notifications now are partially working they seem to be duplicating. ![IMG_2747](https://private-user-images.githubusercontent.com/100245448/328482887-9ae24d37-e6f8-4b9d-b97d-6c26c365b6ee.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTMxODksIm5iZiI6MTcxNTA5Mjg4OSwicGF0aCI6Ii8xMDAyNDU0NDgvMzI4NDgyODg3LTlhZTI0ZDM3LWU2ZjgtNGI5ZC1iOTdkLTZjMjZjMzY1YjZlZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTQ0MTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM4YWU3ZmQ3MjA4MWNkZWFiMGY2MmVhNTY0MGNlN2NmZmFkNGI3MDNmNTVkYTM5MzQzZmJlY2E1ZDM2MDg0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O6SZgwz-uQCgpdOW9hISRwttQA1AHN3POMm9uAzw5OY)

Thanks @SputNikPlop pushed a fix for this https://github.com/muxable/rtchat/pull/1242

Let me know if it still happens after a few minutes?

**Comment by SputNikPlop** [comment]
> Let me know if it still happens after a few minutes?
Appears to be working now
![IMG_2752](https://github.com/muxable/rtchat/assets/100245448/52dfc34d-dc41-4216-af49-ef09ea8e91dc)

**Comment by kevmo314** [comment]
Thanks!
