### ISSUE TITLE
Test TTS in the background

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#1183]
Enable TTS on a popular channel (maybe try jinnytty or something) and make sure that TTS keeps working even if RealtimeChat is in the background. The notification should show and TTS should continue to play until the app is reopened.

**Comment by jlw4049** [comment]
On android the TTS seems to work well with the app in the back-ground. However, there is no notification, so I'll look into that.

**Comment by jlw4049** [comment]
Completed
