### ISSUE TITLE
Disable TTS when stream goes offline

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#1185]
You can check if the message is a `StreamStateEvent` and disable TTS accordingly.

https://github.com/muxable/rtchat/blob/2ca0e7224ff603c3a8e210fa20a8ddda01cafcae/lib/models/tts.dart#L136

**Comment by SputNikPlop** [comment]
@kevmo314 What about disabling TTS when a streamer raids as well?

**Comment by kevmo314** [comment]
That would probably get caught by the queue full feature in the other ticket.
