### ISSUE TITLE
Disable TTS if the queue gets too long

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#1186]
Update the TTS enqueueing logic to do the following:

1. If the queue is more than 10 items, disable reading the usernames.
2. If username reading is already disabled and the queue is at 20 items, disable TTS and read a "There are too many messages. TTS Disabled" messsage.
3. If the queue goes back to zero items, enable reading the username.

**Comment by jlw4049** [comment]
Once merged this should close this right?

https://github.com/muxable/rtchat/issues/1184
