### ISSUE TITLE
App not loading on android

### ISSUE THREAD

**Issue by pixelexio** [muxable/rtchat#1295]
App stops at loading screen with the chat bubble and muxalble - nothing happens.
I have tried reinstalling app, restarting app and phone etc.

**Comment by pixelexio** [comment]
![chat not loading](https://github.com/user-attachments/assets/84f0265b-9ea8-4ef0-877e-6807f6d241a0)

**Comment by SputNikPlop** [comment]
Are you able to load google.com if you use Chrome?

**Comment by pixelexio** [comment]
Yes, works like a charm. I have internet. Is there any way to get a debug log on android?

**Comment by SputNikPlop** [comment]
> Yes, works like a charm. I have internet. Is there any way to get a debug log on android?

Seems like muxfd might be able to help more here https://discord.com/channels/823598483255722056/846232108930564126/1268317259680583760 to get you a solution

**Comment by pixelexio** [comment]
> > Yes, works like a charm. I have internet. Is there any way to get a debug log on android?
> 
> Seems like muxfd might be able to help more here https://discord.com/channels/823598483255722056/846232108930564126/1268317259680583760 to get you a solution

I can't join channel, maybe I need server invite?

**Comment by SputNikPlop** [comment]
> I can't join channel, maybe I need server invite?

Sure https://discord.gg/UKHJMQs74u doesn't appear that this is an isolated issue as I mixed you up with another user having another similar issue

**Comment by Densvenske** [comment]
Have same problem here and have shared it on Discord  and have 2 friends with same problem :(

**Comment by pixelexio** [comment]
Now there is even another having same problems on two phones - posted on discord.. please help!
