### ISSUE TITLE
Badges alignment 

### ISSUE THREAD

**Issue by ryansng** [muxable/rtchat#216]
Moderator and VIP badges not aligned with username
![image](https://user-images.githubusercontent.com/86465073/131239977-6c045ca9-e74f-482a-b453-147796fcf2f4.png)

Moderator badge for streamelements aligns properly
![image](https://user-images.githubusercontent.com/86465073/131240025-b395b399-9d57-43f3-a648-2618c195120d.png)

**Comment by kevmo314** [comment]
Is this happening on `main`? I'm not able to reproduce this.

**Comment by ryansng** [comment]
Yes on the latest version of main (#214?), it is the same for all font sizes, just tested it again. I'm using Pixel 4, I will try to create a new Pixel 4 virtual device and see if it is still the same.

**Comment by ryansng** [comment]
Virtual device setup:
![image](https://user-images.githubusercontent.com/86465073/131271079-310488f6-87e8-4062-abb8-ff4e192a4b43.png)
![image](https://user-images.githubusercontent.com/86465073/131271083-7e72d64d-1817-4600-80c6-0b3a88151ccf.png)
![image](https://user-images.githubusercontent.com/86465073/131271088-8472988b-e4b2-49e0-a20a-d71094689afd.png)

When inside realtimechat app:
1. Settings -> Chat History -> Twitch Badge Settings -> Select All. 
2. Find a channel on home screen

![image](https://user-images.githubusercontent.com/86465073/131271247-d8e7cf0e-2938-4686-8740-e34e73f907e4.png)
