### ISSUE TITLE
Removing the webview by default for ios support

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#280]
For iOS, we need to remove the activity feed tab and the associated settings.

**Comment by SputNikPlop** [comment]
Podfile dependencies needs to be looked into some are too old.

**Comment by juaoose** [comment]
![image](https://user-images.githubusercontent.com/994594/157356090-8532630a-0b89-4c4d-a4f3-26d415a6aeae.png)

**Comment by kevmo314** [comment]
Done in the new UI cleanup
