### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by OutdoorIRL** [muxable/rtchat#29]
I did a 3 hour stream playing with rtchat and noticed it crashing 5-7 times randomly. Not sure if its because I am running a youtube preview tab or/and with TTS enabled. I am on android Samsung Galaxy S20 Ultra on android 11, on latest OS patch and latest version of rtchat.

**Comment by kevmo314** [comment]
We've probably addressed this with crash logs, let us know if you're still running into it and the twitch account associated.
