### ISSUE TITLE
tts plays whole chat history

### ISSUE THREAD

**Issue by juaoose** [muxable/rtchat#358]
I think this only happens once (every install), and tts plays everything from the beginning of times.

**Comment by juaoose** [comment]
Yeah i think thats when it happens

**Comment by juaoose** [comment]
Also when you switch channel via the new raid widget

**Comment by kevmo314** [comment]
Ohh we should probably disable tts when a channel change event happens

**Comment by kevmo314** [comment]
Looking into this I think we should also track the message received timestamp in the tts model and only play messages in the future. This is happening because if the messages get redownloaded for whatever reason like the widget gets refreshed, it'll trigger all of them through tts.
