### ISSUE TITLE
[layout] input doesn't defocus

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#5]
The "Send a message..." input doesn't defocus for some reason after the keyboard is closed. This causes the keyboard to pop up whenever the main page is navigated to, which is mildly annoying.

**Comment by ryansng** [comment]
Tried using the package (https://pub.dev/packages/flutter_multi_formatter) from Reference link 2. Added the code from (https://github.com/caseyryan/flutter_multi_formatter/blob/master/lib/utils/unfocuser.dart) to `lib/components/unfocuser.dart`. Wrapped `TextField()`, `DefaultTabController()`, `MultiProvider()`, and it does not work. I might have done something wrong so it is advisable to redo this part. 

Tried wrapping the root widget (?) `MultiProvider()` in `main.dart` with 
```
Listener(
      onPointerDown: (PointerDownEvent event) =>
          FocusManager.instance.primaryFocus?.unfocus(),
      child: MultiProvider( ... )
)
```
It works for the most part except when the `TextField` hasFocus and it is tapped. It is also not possible to edit the text inside by tapping the text as this will unFocus the `TextField`.

**Comment by kevmo314** [comment]
Maybe we can detect if the touch target is a `TextField` and ignore it if so? This sounds quite hacky though. I'll play around with it a bit as well.

re: the `MultiProvider()` we can wrap the `HomeScreen()` widget in this thing to make it a little less intrusive.
