### ISSUE TITLE
[chat_history] use new material over scroll effect

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#500]
The latest versions of Android have a new rubbery over scroll effect. It's behind a flag in flutter right now, we should enable it.

**Comment by SputNikPlop** [comment]
@kevmo314 @juaoose is this what you are want?
https://github.com/flutter/flutter/issues/104437

**Comment by SputNikPlop** [comment]
https://discord.com/channels/823598483255722056/845327843659218944/1092596236403625984
