### ISSUE TITLE
command bar overflow

### ISSUE THREAD

**Issue by juaoose** [muxable/rtchat#548]
The command bar (!) will overflow on smaller screens whenever the stream preview is open.

**Comment by SputNikPlop** [comment]
The command bar (!event and other commands) used to stack vertically. To reproduce increase the system zoom on your device basically try to get the keyboard to push over the stream preview (vertical and landscape).

I think what we'd want to do to fix this is move the stream preview out of the way with a translate if it's blocking anything, it's not so easy though.

**Comment by duncanodhis** [comment]
This is what i saw 
![WhatsApp Image 2024-01-11 at 13 09 37](https://github.com/muxable/rtchat/assets/45081961/cdd9bd35-91dd-4689-96ac-f5f36a104cbf)
![WhatsApp Image 2024-01-11 at 13 09 36](https://github.com/muxable/rtchat/assets/45081961/0f82a292-0523-4a88-b377-fd9dd020d414)

**Comment by juaoose** [comment]
> This is what i saw ![WhatsApp Image 2024-01-11 at 13 09 37](https://private-user-images.githubusercontent.com/45081961/295873309-cdd9bd35-91dd-4689-96ac-f5f36a104cbf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODYxMTAsIm5iZiI6MTcwNDk4NTgxMCwicGF0aCI6Ii80NTA4MTk2MS8yOTU4NzMzMDktY2RkOWJkMzUtOTFkZC00Njg5LTk2YWMtZjVmMzZhMTA0Y2JmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNTEwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzliNTczOGE0MTE5MTNhMDEyMjU1YTcyNDc5ZTE5YTM4ZTgyN2I0ZjU4YTI5MDcxNWI2YWY5N2JiNThkZThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CUL09XABXj-PT6nzosdKvmZ9IJo7-8bHHnhU3QJVUqA) ![WhatsApp Image 2024-01-11 at 13 09 36](https://private-user-images.githubusercontent.com/45081961/295873323-0f82a292-0523-4a88-b377-fd9dd020d414.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODYxMTAsIm5iZiI6MTcwNDk4NTgxMCwicGF0aCI6Ii80NTA4MTk2MS8yOTU4NzMzMjMtMGY4MmEyOTItMDUyMy00YTg4LWIzNzctZmQ5ZGQwMjBkNDE0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNTEwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWI2Y2RlYTE0ZTEyOWEzMmIzOThiMTI2OWIwNzdjM2JkYWM4NzgxN2E0NDkyZGMxODA4ODM4NDdlNDBhYjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eQIhPWk36gxzOqO10bVdqc0Lny6cFMiWUneAsLShMa0)

I believe you're missing the last couple of steps:
1. Send a "command", for example `!hi`.
2. After that you will have a new widget on top of the chat box which is what caused the overflow (I believe I only saw it on lower resolutions and on portrait mode)

**Comment by SputNikPlop** [comment]
This now adapts properly
