### ISSUE TITLE
Command bar not scrollable

### ISSUE THREAD

**Issue by chungwwei** [muxable/rtchat#555]
https://github.com/muxable/rtchat/blob/main/lib/screens/home.dart#L174
https://github.com/muxable/rtchat/blob/main/lib/components/message_input.dart#L132

Swiping opens the drawers, but it's also the same gesture to scroll through commands. 
Flutter seems to prioritize opening the drawers in the current codebase.

**Comment by juaoose** [comment]
This is also affecting stream preview resizing on landscape mode.

**Comment by kevmo314** [comment]
@cswills can you take a look and see if we can override?

**Comment by cswills** [comment]
I'm on it.

**Comment by kevmo314** [comment]
We addressed this by removing all instances of horizontal scrolling
