### ISSUE TITLE
[eventsub] duplicate subscription messages

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#644]
![Screenshot_20220825-170015](https://user-images.githubusercontent.com/511342/186768551-3f2e532c-0518-4557-b8e3-86c2f4efe4d2.png)

We seem to get duplicate subscription messages for first-time subs. Probably the second should be ignored?

**Comment by juaoose** [comment]
Seems related, maybe using irc instead?

https://discord.com/channels/504015559252377601/776875921654546463/937410968567300137

**Comment by kevmo314** [comment]
That's pretty annoying. Maybe we should hide the message in the UI if there's no attached text instead? I don't think we should switch to IRC, eventsub is more reliable.
