### ISSUE TITLE
[home] update title font to Hansen

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#652]
We have mocks for RealtimeKit here: https://www.figma.com/file/nDbJEtM3ZH3IpSazX7zR3D/RealtimeKit-Control?node-id=0%3A1

We should update the RealtimeChat home page to use the same Hansen font. The color should also be updated but let's leave it white for now until we figure out what to do with the blue accent.

**Comment by SputNikPlop** [comment]
> Let's try it out, maybe in a separate PR, but it might be too bold. Poppins is a little softer.

I tried it earlier today it felt a little too strong.
