### ISSUE TITLE
[autocomplete] command autocomplete ui seems odd

### ISSUE THREAD

**Issue by kevmo314** [muxable/rtchat#805]
![image](https://user-images.githubusercontent.com/511342/197829369-57e12045-72db-40c4-9bc0-fa2163b86a88.png)

Looks like the input field also gets pushed off screen?

**Comment by chungwwei** [comment]
I think its okay.

if you drag the webview down about half screen, it'll push off the InputField and the commands.
user can just drag the webview up so that those frontend elements become visible again.
