### ISSUE TITLE
[chat] qr codes

### ISSUE THREAD

**Issue by SputNikPlop** [muxable/rtchat#904]
https://clips.twitch.tv/WealthySwissPresidentNerfRedBlaster-1uszjVbudlI7fQpi

**Comment by ryansng** [comment]
I remember writing code for this exact use-case with real time chat logo in the QR code but idea was gutted ):

**Comment by ryansng** [comment]
![image](https://user-images.githubusercontent.com/86465073/215061454-5b3d1d88-1358-4483-bb73-e0a2dd11825c.png)
![image](https://user-images.githubusercontent.com/86465073/215061466-79593c63-66a6-46e1-9d6c-4671f81fd6cc.png)

**Comment by SputNikPlop** [comment]
> I could take this up again at some point if it's not urgent

Feel free there is no rush at all on this at all.

**Comment by SputNikPlop** [comment]
![IMG_1465](https://github.com/muxable/rtchat/assets/100245448/8842175e-436d-4628-8970-073da83382a7)
![IMG_1466](https://github.com/muxable/rtchat/assets/100245448/74b1aa4d-d6de-4e98-a08c-2da6c7cf312c)
@kevmo314 Which do you like more I am leaning towards the second as it look more like a card
