### ISSUE TITLE
[chat_history] color variation based on tier

### ISSUE THREAD

**Issue by SputNikPlop** [muxable/rtchat#929]
Brought up in #831

**Comment by VaishaliDesai** [comment]
I can take this up!

**Comment by kevmo314** [comment]
> I can take this up!

@VaishaliDesai That would be great! Are you on our Discord?

**Comment by VaishaliDesai** [comment]
> > I can take this up!
> 
> @VaishaliDesai That would be great! Are you on our Discord?

Yes, I'm new to Discord and username is vaishalidesai#4008

**Comment by VaishaliDesai** [comment]
Would it be possible to get more information on the issue please?

**Comment by kevmo314** [comment]
@VaishaliDesai I added you to the engineering role on Discord. The gist of this feature request can be found in https://github.com/muxable/rtchat/pull/831

Right now, the "Tier 1" bubble is only a single color for all tiers on Twitch (Tier 1, Tier 2, Tier 3). We'd like to change the bubbles to be different colors, specifically #ffea00 for Tier 3 and #d2d2e6 for Tier 2. @SputNikPlop are these colors correct? If you have any questions getting the app running, let us know in #engineering on Discord and we can help there too!

**Comment by SputNikPlop** [comment]
@kevmo314 Yes those are correct and match the default ones given by twitch.

**Comment by VaishaliDesai** [comment]
Thank you both @kevmo314 and @SputNikPlop for the confirmation on colors. I have opened up a [PR](https://github.com/muxable/rtchat/pull/954) for this issue
